### ISSUE TITLE
Make your membership public

### ISSUE THREAD

**Issue by sparrell** [OpenC2-org/openc2-org#1]
### PROBLEM

Everyone who is a member of openc2-org defaults to 'private' membership - ie members are only visible to other members. So right now openc2 appears to be an organization of two (Joe and Duncan). Since there is much broader participation, it would benefit openc2 if those willing would 'go public'. It may worth discussing whether 'private' membership (ie not publicly visible) should be allowed.

---
### POTENTIAL SOLUTION

Those who are willing can go in and change their membership from private to public. 
1. Go to OpenC2-org (one up from this repo, click on the word OpenC2-org)
2. click on the "People" tab
3. go to your name and click the dropdown on 'private'
4. click public

**Comment by romanojd** [comment]
That's a great suggestion. I wasn't actually aware that members were not visible to each other. Since I can see everybody, I assumed that was the default. I don't see an option to change the default visibility settings.

Along the same lines, I noticed that "teams" were not visible either. So I opened them up, too.

**Comment by sparrell** [comment]
Members can see members. Going public allows non-members, eg prospective members, to see members

**Comment by romanojd** [comment]
We're up to 8 (of 40+) people with public membership.
